import { useEffect, useState } from "react";

import { CardList, CardProps, Heading, SearchBox } from "@/components/home";
import { useAxios } from "@/hooks/useAxios";
import { Loading } from "@/layout";

export const Home = () => {
   const { data, loading, error, isSubmitted } = useAxios<CardProps[]>("get", "/posts/get-posts");
   const [searchText, setSearchText] = useState("");
   const [searchPosts, setSearchPosts] = useState<CardProps[] | null>(null);

   useEffect(() => {
      if (!data?.length) return;

      const filterData = data.filter((post) => {
         return (
            post.name.toLowerCase().includes(searchText.toLowerCase()) ||
            post.prompt.toLowerCase().includes(searchText.toLowerCase())
         );
      });
      setSearchPosts(() => filterData);
   }, [searchText]);

   return (
      <section className="home-section">
         <Heading
            title="The Community Showcase"
            subTitle="Browse Through A Collection Of Imaginative And Visually Stunning Images Generated By DALL-E AI"
         />

         <SearchBox searchText={searchText} setSearchText={setSearchText} />

         {loading && (
            <Loading
               isSubmitted={isSubmitted}
               loading={loading}
               error={error}
               message={data}
               hideSubLoadingText
               subLoading
            />
         )}

         {!loading && (
            <div className="mt-4 w-full">
               <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
                  {searchText && <CardList data={searchPosts?.reverse()} title="No Search Results Found" />}
                  {!searchText && <CardList data={data?.reverse()} title="No Posts Found" />}
               </div>
            </div>
         )}
      </section>
   );
};
